name: CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
      - name: Test the app
        run: ./gradlew test
  