### Continuous Integration
# 
# This file is inspired by 
# https://www.raywenderlich.com/19407406-continuous-delivery-for-android-using-github-actions

name: CI
on: [pull_request, push]
jobs:

  ## Build the app and run unit tests
  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
      - name: Test the app
        run: ./gradlew test

  ## Run tests on an Android Simulator 
  # We use macos as it has hardware acceleration for that
  android_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
  